# Une scène concrète par carte : le lanceur de la carte, reconnaissable, fait l'action décrite.
# {garde}, {lame}... sont remplacés par la description du héros (voir LOOKS). Ennemis = golems de basalte.
LOOKS = {
    "garde": "the Guard, a knight in blue-steel plate armor with a halberd and a blue tower shield",
    "lame": "the Blade, a slim hooded assassin in black with a red scarf and twin curved daggers",
    "oracle": "the Oracle, a purple-robed mage with a wide pointed hat and a golden lantern staff throwing ember fire",
    "artificier": "the Artificer, a teal-clad engineer with goggles, a wrench, powder barrels and bombs",
    "moine": "the Monk, a green-robed barefoot martial monk fighting with open palms and fists",
    "trappeur": "the Trapper, an ochre-leather hunter with a harpoon, nets and a crossbow",
    "tidiane": "Tidiane, a masked artisan duelist in a magenta hooded coat with a white porcelain mask, wielding a brush-shaped blade that splashes blue, black and red ink",
    "receleur": "the Fence, a grey-blue cloaked thief with many pockets, a loot sack and a wrench",
}
FOE = "a cracked basalt golem with glowing ember cracks"

S = {
    # ---------------- Garde
    "frappe": "{garde} swings his halberd down on {foe}",
    "pavois": "{garde} braces behind his raised tower shield, sparks glancing off it",
    "charge": "{garde} charges shield-first across a bridge, ramming {foe} backwards",
    "defi": "{garde} bangs his halberd on his shield, taunting several golems who turn toward him",
    "rempart": "{garde} plants his shield, a blue barrier of light covering two allies behind him",
    "marteau": "{garde} smashes {foe} with a huge lock-gate hammer, sending it flying back",
    "bastion": "{garde} kneels behind his shield, calm, a blue glow around him",
    "bouclier": "{garde} hurls his round shield like a discus at {foe}",
    "crochet": "{garde} hooks {foe} with a long boat hook and drags it toward him",
    "forteresse": "{garde} stands on a rampart, a translucent blue fortress of light rising around the party",
    # ---------------- Lame
    "estoc": "{lame} stabs {foe} in the back with a dagger",
    "ombre": "{lame} vanishes in black smoke and reappears on a higher ledge",
    "double": "{lame} slashes {foe} twice with both daggers, two red arcs",
    "venin": "{lame} coats a dagger with dripping green poison, then cuts {foe}",
    "couperet": "{lame} brings down a heavy cleaver on {foe}, already wounded",
    "ricochet": "{lame} throws a dagger that bounces between two golems",
    "fente": "{lame} lunges in a long straight dash through the air, blade first",
    "embuscade": "{lame} crouches in the shadows behind a pillar, waiting to strike",
    "coupures": "{lame} surrounded by a whirl of countless tiny floating blades",
    # ---------------- Oracle
    "braise": "{oracle} throws a bolt of ember fire from her lantern staff at {foe}",
    "seve": "{oracle} heals a wounded ally with green sap-like light from her staff",
    "colonne": "{oracle} calls down a column of ash and fire onto a group of golems",
    "maree": "{oracle} summons a wave of water that sweeps {foe} into a canal",
    "surveil": "{oracle} gazes into her lantern, glowing cards of light floating before her",
    "delve": "{oracle} pulls pages of burning spells from a pile and hurls them at {foe}",
    "arc": "{oracle} releases a chain of ember lightning jumping between three golems",
    "echo": "{oracle} casts a spell whose glowing rune repeats twice in the air",
    "cendres": "{oracle} standing under a rain of glowing ashes that burn the golems around her",
    "lotus": "{oracle} opening a giant glowing lotus of light that heals the whole party",
    # ---------------- Artificier
    "grenade": "{artificier} lobs a hissing grenade at a group of golems",
    "baril": "{artificier} rolls a black powder barrel into place, fuse ready",
    "etincelle": "{artificier} flicks a spark from his wrench at a distant powder barrel, which explodes",
    "rivet": "{artificier} hammers a glowing rivet into {foe} with his wrench, metal plates on his arm",
    "tourelle": "{artificier} assembles a small brass turret that fires at {foe}",
    "surcharge": "{artificier} overcharging a crackling engine, sparks flying from his goggles",
    "mortier": "{artificier} fires a mortar, the shell arcing high toward far golems",
    "atelier": "{artificier} at a makeshift workshop full of barrels, tools and blueprints",
    # ---------------- Moine
    "paume": "{moine} strikes {foe} with an open palm, a ring of air bursting out",
    "poing": "{moine} hammers {foe} with a heavy downward fist",
    "tourbillon": "{moine} spins in a whirlwind kick hitting golems all around him",
    "bond": "{moine} leaps high like a crane over a broken wall",
    "souffle": "{moine} meditating, breathing out a calm green mist that heals him",
    "ressac": "{moine} pushes {foe} away with a palm strike that carries a wave of water",
    "cent": "{moine} unleashes a hundred-fist flurry on {foe}, motion trails everywhere",
    "voie": "{moine} in a fighting stance, three glowing fist marks floating around him",
    # ---------------- Trappeur
    "fleche": "{trappeur} shoots a heavy weighted crossbow bolt at {foe}",
    "piege": "{trappeur} sets a steel jaw trap on the ground",
    "marque": "{trappeur} paints a red hunter's mark on {foe} with an arrow",
    "filet": "{trappeur} throws a weighted net over {foe}",
    "pluie": "{trappeur} fires a volley of arrows raining down on golems",
    "harpon": "{trappeur} harpoons {foe} and drags it toward him with the rope",
    "perforant": "{trappeur} fires a piercing bolt that punches straight through {foe}'s stone armor",
    "instinct": "{trappeur} crouched on a ledge watching his traps, eyes glowing like a predator",
    # ---------------- Tidiane
    "esquisse": "{tidiane} slashes {foe} with a quick sketch-like stroke of their brush-blade",
    "recul": "{tidiane} steps back, analyzing, a shield of blue ink lines in front of their",
    "journal": "{tidiane} writing in a leather journal, ink pages floating around",
    "pacte": "{tidiane} strikes {foe} with blue, black and red ink, paying with their own blood",
    "arbo": "{tidiane} surrounded by branching glowing thought lines like a tree",
    "wavedash": "{tidiane} sliding low across the floor while slashing {foe}",
    "punchline": "{tidiane} lands a decisive final blow on {foe}, big ink splash",
    "truecombo": "{tidiane} chaining three unbroken slashes on {foe}",
    "monster": "{tidiane} crushing an energy drink can, lightning crackling around their",
    "nuit": "{tidiane} awake at night by candlelight, drawing cards under tired eyes",
    "transmutation": "{tidiane} turning {foe}'s ember into healing ink flowing back to their",
    "dette": "{tidiane} striking {foe} hard while red debt-like chains wrap their arm",
    "dsm": "{tidiane} dissecting {foe} with analytic blue ink diagrams and a target mark",
    "contreanalyse": "{tidiane} pinning {foe} with lines of blue ink while a shield forms around their",
    "troisvoix": "{tidiane} with three ghostly echoes of themself in blue, black and red attacking together",
    "break174": "{tidiane} delivering a massive rhythmic strike, sound waves like drum beats around the impact",
    "purerage": "{tidiane} in a furious double slash, red ink exploding",
    "potentiel": "{tidiane} unleashing a gigantic strike, blue black and red energy erupting",
    "revelation": "{tidiane} bathed in a sudden revelation of light, wounds closing",
    "hyperfocus": "{tidiane} in total concentration, the world blurred, a sharp glowing blade",
    "dnb": "{tidiane} fighting to an invisible drum and bass rhythm, speakers of light and sound waves",
    "obsession": "{tidiane} obsessively sharpening their brush-blade, spiraling ink around their",
    # ---------------- Receleur
    "larcin": "{receleur} snatches an item from {foe}'s belt and stabs it",
    "cle": "{receleur} whacks {foe} with a big wrench",
    "bricolage": "{receleur} tinkering a gadget out of scraps from his sack",
    "camelote": "{receleur} throwing a storm of junk from his sack at {foe}",
    "crochetage": "{receleur} picking a lock on {foe}'s chest-plate from a distance with a hooked tool",
    "recyclage": "{receleur} breaking an old gadget into glowing parts",
    "contrefacon": "{receleur} forging a copy of a gadget on a workbench, two identical items",
    "coupdesac": "{receleur} swinging his heavy loot sack into {foe}",
    "etal": "{receleur} unrolling a stall of freshly made gadgets",
    "lecasse": "{receleur} cracking open {foe} like a safe, stealing a glowing item",
    "marchenoir": "{receleur} dealing shady goods under a lantern in a dark alley",
    "poches": "{receleur} pulling endless items from bottomless pockets",
    # ---------------- guildes (deux héros ensemble)
    "g_etau": "{garde} pins {foe} with his shield while {lame} stabs it from behind",
    "g_contrepied": "{garde} blocks behind his shield while {lame} slips around the side",
    "g_tenaille": "{garde} and {lame} strike {foe} from both sides at once",
    "g_appat": "{garde} stands exposed as bait while {lame} waits in the shadows",
    "g_releve": "{garde} and {lame} swapping places mid-battle, a blue shield flash",
    "g_benir": "{oracle} blessing {garde} with warm golden light",
    "g_lumiere": "{oracle} and {garde} raising a dome of steel-colored light over the party",
    "g_litanie": "{oracle} chanting beside {garde}, healing light turning into armor plates",
    "g_lance_aube": "{garde} throws a spear of dawn light that {oracle} set ablaze, at {foe}",
    "g_seuil": "{garde} and {oracle} standing on a glowing sacred spring",
    "g_sacs": "{garde} and {artificier} stacking sandbags and a powder barrel",
    "g_parapet": "{garde} and {artificier} behind a quick wooden parapet",
    "g_pavois_piege": "{garde} holds a shield rigged with explosives by {artificier}",
    "g_charge_belier": "{garde} and {artificier} charging with a battering ram into {foe}",
    "g_mantelet": "{artificier} and {garde} raising a cracked stone pillar as cover",
    "g_frappe_roc": "{garde} and {moine} striking {foe} together, stone-hard fists",
    "g_garde_haute": "{moine} and {garde} both in a high guard stance",
    "g_paume_fer": "{moine} strikes {foe} with an iron palm while {garde} covers him",
    "g_roc": "{garde} and {moine} standing like a rock, armor glowing",
    "g_phalange": "{moine} leaps next to {garde}, both locking shields and fists",
    "g_battue": "{garde} beats bushes pushing {foe} toward {trappeur}",
    "g_palissade": "{trappeur} sets a trap behind {garde}'s shield",
    "g_rabatteur": "{garde} shoves {foe} into a trap set by {trappeur}",
    "g_enclos": "{garde} surrounded by traps laid by {trappeur}",
    "g_epieu": "{trappeur} and {garde} plant a sharpened stake in the ground",
    "g_douche": "{garde} and {tidiane} under a freezing waterfall, gritting teeth",
    "g_discipline": "{tidiane} training with {garde}, disciplined sword drills at dawn",
    "g_callus": "{garde} and {tidiane} with hardened hands and scars, armored",
    "g_cle_donjon": "{tidiane} holds up a glowing dungeon key next to {garde}",
    "g_parry": "{tidiane} parries {foe}'s blow with a perfect flash, {garde} behind their",
    "g_fouille": "{garde} searches {foe} while {receleur} grabs its item",
    "g_consigne": "{receleur} hands items to {garde}, his shield hung with gear",
    "g_saisie": "{garde} and {receleur} seizing a glowing item from {foe}",
    "g_coffre_fort": "{garde} guarding a heavy safe while {receleur} counts loot",
    "g_ferraille": "{garde} holds a shield made of scrap metal welded by {receleur}",
    "g_murmure": "{oracle} whispers to {lame}, green poison mist drifting",
    "g_dard": "{lame} throws an ember-tipped poison dart lit by {oracle}",
    "g_brume_noire": "{oracle} opens black mist from which {lame} appears behind {foe}",
    "g_venin_braise": "{oracle} and {lame} burning poison into {foe}, green and orange flames",
    "g_lecture_ombres": "{oracle} reads shadow cards held by {lame}",
    "g_petard": "{lame} tosses a firecracker from {artificier} at a barrel next to {foe}",
    "g_amorce": "{artificier} places a barrel while {lame} sneaks behind {foe}",
    "g_meche": "{lame} teleports behind {foe} and sticks a lit charge from {artificier} on it",
    "g_poudre_aveuglante": "{artificier} and {lame} in a cloud of blinding powder",
    "g_detonateur": "{lame} throws a dagger that triggers a barrel by {artificier}",
    "g_rafale": "{moine} and {lame} hit {foe} with a quick double flurry",
    "g_pas_vent": "{lame} and {moine} dash through the wind leaving leaves swirling",
    "g_tourbillon_acier": "{lame} spins like a steel whirlwind taught by {moine}",
    "g_grue_ombre": "{moine} leaps like a crane into shadows with {lame}",
    "g_petales": "{lame} and {moine} striking a thousand times in a storm of petals",
    "g_pistage": "{trappeur} reads tracks while {lame} marks {foe}",
    "g_carreau": "{trappeur} fires a crossbow bolt, {lame} beside him",
    "g_avis": "{lame} nails a wanted poster, {trappeur} marks the target",
    "g_carreau_poison": "{trappeur} fires a poison-coated bolt prepared by {lame}",
    "g_piege_ombre": "{lame} and {trappeur} hiding a shadow trap under dark mist",
    "g_jab": "{tidiane} throws a fast jab at {foe}, {lame} ready behind",
    "g_dash": "{lame} and {tidiane} dash-cancel across the floor",
    "g_whiff": "{foe} misses and {tidiane} punishes it instantly with {lame}",
    "g_muda": "{tidiane} and {lame} unleashing a barrage of countless blows",
    "g_frames": "{tidiane} reads {foe}'s movement frame by frame, {lame} waiting",
    "g_coupe_bourse": "{lame} cuts {foe}'s purse while {receleur} catches it",
    "g_ombre_quai": "{lame} appears behind {foe} on the night docks, {receleur} lookout",
    "g_tire": "{receleur} and {lame} pickpocketing {foe} in one quick move",
    "g_enduite": "{receleur} coats {lame}'s blade with poison from a vial",
    "g_filiere": "{receleur} and {lame} passing stolen goods hand to hand",
    "g_etincelle_bleue": "{oracle} and {artificier} launch a blue electric spark",
    "g_braise_poudre": "{oracle} ignites powder thrown by {artificier}, cross-shaped blast",
    "g_arc_volt": "{artificier} and {oracle} unleash lightning that sets off barrels",
    "g_colonne_s": "{oracle} and {artificier} calling an overcharged column of fire",
    "g_brasero": "{artificier} carries a lit brazier, {oracle} kindling it",
    "g_souffle_braise": "{moine} breathes ember fire lit by {oracle} at {foe}",
    "g_mantra": "{oracle} and {moine} chanting a mantra, calm glow",
    "g_paume_guer": "{moine} strikes {foe} while healing light flows to {oracle}",
    "g_meditation": "{oracle} and {moine} meditating together, healing the party",
    "g_braise_int": "{moine}'s fists burn with inner ember fire from {oracle}",
    "g_oeil_ouvert": "{oracle} opens a glowing eye above {trappeur} marking {foe}",
    "g_fleche_rune": "{trappeur} shoots a rune-inscribed arrow enchanted by {oracle}",
    "g_tir_augural": "{oracle} foresees the shot as {trappeur} fires from far away",
    "g_rune_chasse": "{oracle} draws a hunting rune on a trap set by {trappeur}",
    "g_presage": "{oracle} and {trappeur} under an omen sky, all golems marked",
    "g_page": "{tidiane} and {oracle} looking at a blank glowing page",
    "g_rature": "{tidiane} crosses out {foe} with an ink stroke, {oracle} glowing",
    "g_relecture": "{oracle} and {tidiane} rereading old pages that turn into cards",
    "g_insomnie": "{tidiane} awake by lamplight, {oracle} healing a sleeping ally",
    "g_rechute": "{tidiane} falling and rising again, {oracle} watching over their",
    "g_estampille": "{receleur} stamping an item, {oracle} blessing it",
    "g_fiole_braise": "{oracle} throws an ember vial brewed by {receleur}",
    "g_transmut": "{oracle} transmutes an item held by {receleur} into a fire blast",
    "g_alchimie": "{oracle} and {receleur} brewing potions at an alchemy table",
    "g_expertise": "{receleur} appraising items with a loupe, {oracle} reading",
    "g_poing_poudre": "{moine} punches {foe}, a powder charge from {artificier} exploding",
    "g_meche_lente": "{artificier} places a barrel with a slow fuse beside {moine}",
    "g_gantelet": "{moine} wearing an explosive gauntlet built by {artificier}",
    "g_canon": "{moine} fires a cannon blast punch, recoil pushing him back",
    "g_rythme": "{artificier} hammering at a forge to the rhythm of {moine}'s strikes",
    "g_leurre": "{artificier} and {trappeur} set up a noisy decoy luring golems",
    "g_barrage": "{trappeur} fires at a barrel near {foe} placed by {artificier}",
    "g_mine_fil": "{trappeur} stretches a tripwire mine made by {artificier}",
    "g_tourelle_guet": "{artificier} and {trappeur} building a watch turret",
    "g_champ": "{trappeur} and {artificier} rigging a field of traps and barrels",
    "g_croquis": "{tidiane} sketches a blueprint, {artificier} builds from it",
    "g_brouillon": "{tidiane} and {artificier} roughing a draft beside a powder barrel",
    "g_geste": "{artificier} and {tidiane} perfecting a technical gesture at a workbench",
    "g_burnout": "{tidiane} burning out, overheating machines around {artificier}",
    "g_174": "{tidiane} and {artificier} blowing barrels in rhythm at 174 bpm",
    "g_clou": "{artificier} and {receleur} throwing rusty nails at {foe}",
    "g_tonnelier": "{receleur} and {artificier} building a small powder keg",
    "g_demontage": "{receleur} dismantles a gadget, {artificier} turns it into a barrel",
    "g_bombe_art": "{artificier} and {receleur} crafting homemade fuse bombs",
    "g_tour_recup": "{receleur} and {artificier} building a scrap turret",
    "g_balayage": "{moine} sweeps {foe}'s legs, {trappeur} ready with a rope",
    "g_garrot": "{trappeur} strangles {foe} with a garrote, {moine} holding it",
    "g_lievre": "{moine} kicks {foe} into a trap set by {trappeur}",
    "g_predateur": "{moine} leaps like a predator on {foe}, {trappeur} watching",
    "g_prise": "{moine} and {trappeur} pinning {foe} to the ground",
    "g_poke": "{tidiane} pokes {foe} at range with their blade, {moine} beside",
    "g_lcancel": "{moine} and {tidiane} landing lightly after a jump attack",
    "g_ewgf": "{tidiane} delivers a lightning uppercut, {moine} in stance",
    "g_shine": "{tidiane} bursts a reflective shine pushing golems away, {moine}",
    "g_techchase": "{moine} and {tidiane} chasing a fallen {foe}",
    "g_bateleur": "{receleur} juggling stolen items as {moine} strikes",
    "g_culbute": "{moine} somersaults while {receleur} grabs a gadget",
    "g_main_preste": "{receleur} steals from {foe} with nimble hands, {moine} distracting",
    "g_jonglage": "{receleur} throws juggled items at {foe}, {moine} flipping",
    "g_saut_marche": "{moine} leaps over {foe} while {receleur} snatches its item",
    "g_reperage": "{trappeur} scouts the ruins with {tidiane}, marking {foe}",
    "g_roulade": "{tidiane} and {trappeur} rolling behind cover",
    "g_pattern": "{tidiane} and {trappeur} studying {foe}'s attack pattern",
    "g_fenetre": "{trappeur} and {tidiane} strike in a narrow window of opportunity",
    "g_iframe": "{tidiane} dodging through an attack as a ghostly afterimage, {trappeur}",
    "g_filet_bracon": "{trappeur} nets {foe} while {receleur} steals its item",
    "g_peaux": "{receleur} and {trappeur} with tanned hides and loot",
    "g_collet_tresor": "{trappeur} sets a snare baited with gold by {receleur}",
    "g_appat_dore": "{receleur} leaves a golden bait, {trappeur} hides a trap",
    "g_trophee": "{trappeur} and {receleur} with hunting trophies and gold",
    "g_reperage_coffre": "{receleur} and {tidiane} spotting a treasure chest",
    "g_coup_main": "{receleur} lends a hand to {tidiane} stealing from {foe}",
    "g_braquage": "{tidiane} and {receleur} robbing a vault of glowing cards",
    "g_recel": "{receleur} sells a glowing emotion in a jar to {tidiane}",
    "g_faux": "{receleur} and {tidiane} creating a fake copy of a glowing card",
}

# légendaires (reprises des planches peintes)
LEG = {
    "g_enclume": "an oath sworn on a glowing anvil: {garde} stands firm while {lame} teleports behind an attacking brute",
    "g_ysolde": "Ysolde, a radiant saint in white and gold at dawn, raising fallen heroes from the water with a halo of light",
    "g_varn": "a massive iron battering ram shaped like a ram's head, pushed by {garde} and {artificier}, smashing enemies back",
    "g_korin": "Korin, a colossal monk in heavy stone-grey armor walking like a mountain, fists glowing",
    "g_maelle": "Maelle, a huntress blowing a horn while {garde} shoves a beast into a spiked trap",
    "g_quarante": "a wounded warrior refusing to fall at dawn, one knee down, surrounded by a shield of red light, gritted teeth",
    "g_octroi": "Mother Bastide, a stern toll-keeper matron in armor at a river gate, taking an item from a bandit",
    "g_nyxa": "Nyxa, a giant unblinking purple eye in the dark sky above a ruined city, dripping green poison",
    "g_zaida": "Zaida, a grinning pyrotechnician woman throwing lit barrels, fireworks bursting behind enemies",
    "g_kaede": "Kaede, a masked shadow ninja woman dashing through the wind, leaving no shadow, cherry-red scarf",
    "g_vesk": "Vesk, a bounty hunter nailing a wanted poster, poisoned target marked with a red sigil",
    "g_justframe": "a frozen instant of a perfect counter-strike, two blades meeting, time stopped, shards of light",
    "g_cador": "Cador, a flamboyant prince of thieves on moonlit docks, stealing a jewel from behind a guard",
    "g_ignar": "Ignar, a huge ember dragon coiled around canal locks, raining fire",
    "g_suien": "Master Suien, an ancient serene monk breathing green healing mist, a hundred ghostly lives around him",
    "g_aelis": "Aelis, a river seer woman with a glowing eye piercing through mist, aiming a harpoon",
    "g_journal": "a giant open leather journal floating, pages turning into glowing cards, {oracle} and {tidiane} reading it",
    "g_oriel": "Lady Oriel, an elegant museum curator restoring broken magical relics on velvet",
    "g_hazan": "Hazan, a muscular monk whose punches explode in gunpowder blasts",
    "g_torvald": "Torvald, a bearded engineer firing a giant ballista from a tower at a far target",
    "g_oeuvre": "a masterpiece being forged: an artisan's hands hammering a glowing weapon at night, sparks everywhere",
    "g_pip": "Pip, a tiny goblin merchant surrounded by an absurd bazaar of junk and exploding barrels",
    "g_tetsu": "Tetsu, a wolf-like river warrior pinning a netted beast to the shore",
    "g_zero": "a combo to the death: {moine} and {tidiane} unleashing a flurry of hits, motion trails",
    "g_linfei": "Lin Fei, an acrobatic monk thief with a hundred pockets, gadgets flying around",
    "g_decoupe": "a hunter butchering a giant fallen beast, trophy glowing, blood-red sunset",
    "g_crane": "the old skull of the shallows, a giant skull reef in the water full of traps and treasures",
    "g_grand_braquage": "the grand heist: {tidiane} and {receleur} cracking a vault of glowing cards at night, three loot bags, blue black and red light",
}

# bienfaits des Anciens (écran « Ancien »)
BOONS = {
    "relique": "an ancient glowing relic resting on a mossy stone pedestal",
    "relique_sang": "a dark relic dripping blood, three candles around it",
    "rare": "a forbidden glowing card floating above an open grimoire",
    "epure": "giant scissors cutting a card in half, paper scraps flying",
    "or": "a heap of gold coins spilling out of an old chest",
    "pvmax": "a small sacred tree with a glowing heart-shaped sap fruit",
    "soin": "a lustral fountain of glowing healing water",
    "forge2": "a master's hammer striking two glowing cards on an anvil",
    "racines": "roots wrapping around a stack of cards, glowing",
    "besace": "a leather satchel overflowing with potions and bombs",
    "place": "a needle sewing an extra pocket onto a satchel",
    "arme": "an ancient ornate weapon planted in stone, glowing",
    "reflet": "a mirror reflecting a card into an identical copy",
    "vocation": "two class emblems, a shield and a lantern, crossed together",
    "memoire": "a river of glowing memories flowing between ruins",
}
